apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: ipfs-kubo
    namespace: default
spec:
    project: default
    source:
        repoURL: https://github.com/mridang/infrastructure-homelab
        targetRevision: HEAD
        path: applications/ipfs-kubo
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
