apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: ipfs
    namespace: default
spec:
    serviceName: "ipfs"
    replicas: 1
    selector:
        matchLabels:
            app: ipfs
    updateStrategy:
        type: RollingUpdate
        rollingUpdate:
            partition: 0
    template:
        metadata:
            labels:
                app: ipfs
        spec:
            initContainers:
                -   name: init-copy-config
                    image: busybox
                    command: [ "sh", "-c", "cp /etc/config/config.json /data/ipfs/config" ]
                    volumeMounts:
                        -   name: ipfs-kubo-data
                            mountPath: /data/ipfs
                        -   name: ipfs-kubo-config
                            mountPath: /etc/config
                            readOnly: true
            containers:
                -   name: ipfs
                    image: ipfs/kubo:latest
                    args: [ "daemon", "--migrate=true", "--agent-version-suffix=docker", "--config-file=/etc/config/config.json" ]
                    ports:
                        -   containerPort: 4001
                        -   containerPort: 4002
                            protocol: UDP
                        -   containerPort: 4003
                        -   containerPort: 5001
                        -   containerPort: 8080
                    env:
                        -   name: IPFS_LOGGING_FMT
                            value: "nocolor"
                            #value: "color"
                        -   name: IPFS_LOGGING
                            #value: "debug"
                            value: "info"
                            #value: "warn"
                            #value: "error"
                            #value: "dpanic"
                            #value: "fatal"
                    volumeMounts:
                        -   name: ipfs-kubo-data
                            mountPath: /data/ipfs
                        -   name: ipfs-kubo-config
                            mountPath: /etc/config
                            readOnly: true
            volumes:
                -   name: ipfs-kubo-data
                    persistentVolumeClaim:
                        claimName: ipfs-kubo-data
                -   name: ipfs-kubo-config
                    configMap:
                        name: ipfs-kubo-config
