apiVersion: apps/v1
kind: Deployment
metadata:
    name: ipfs
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ipfs
    template:
        metadata:
            labels:
                app: ipfs
        spec:
            containers:
                -   name: ipfs
                    image: ipfs/kubo:latest
                    args: [ "--config", "/etc/config/config.json" ]
                    ports:
                        -   containerPort: 4001
                        -   containerPort: 4002
                            protocol: UDP
                        -   containerPort: 4003
                        -   containerPort: 5001
                        -   containerPort: 8080
                    env:
                        -   name: IPFS_PATH
                            value: /data/ipfs
                    volumeMounts:
                        -   name: ipfs-kubo-data
                            mountPath: /data/ipfs
                        -   name: ipfs-kubo-config
                            mountPath: /etc/config
                            readOnly: true
            volumes:
                -   name: ipfs-kubo-data
                    persistentVolumeClaim:
                        claimName: ipfs-kubo-data
                -   name: ipfs-kubo-config
                    configMap:
                        name: ipfs-kubo-config
