# argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: hello-world
    namespace: default
spec:
    project: default
    source:
        repoURL: https://github.com/mridang/infrastructure-homelab
        targetRevision: HEAD
        path: applications/hello-world
    destination:
        server: https://kubernetes.default.svc
        namespace: default
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
